<a href="https://colab.research.google.com/github/PSG4160/6can-do-it/blob/chad/2CH_6%EC%A1%B0_%ED%95%84%EC%88%98%EA%B3%BC%EC%A0%9C_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import seaborn as sns

titanic = sns.load_dataset('titanic')

In [ ]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
titanic.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

# 데이터 통계 지표 설명

### 1. count
- 각 변수의 값이 존재하는 개수를 나타냅니다.
- 데이터셋에 포함된 유효한 데이터 포인트의 수를 보여줍니다.
- 결측치가 없는 값을 파악하는 데 유용합니다.

### 2. mean
- 각 변수의 평균값을 나타냅니다.
- 데이터의 중앙 경향을 파악하는 데 사용됩니다.
- 이를 통해 데이터의 전반적인 수준을 이해할 수 있습니다.

### 3. std
- 표준편차를 나타내며, 데이터가 평균값 주위에 얼마나 분포되어 있는지를 보여줍니다.
- 표준편차가 클수록 데이터의 변동성이 크다는 것을 의미합니다.

### 4. min
- 각 변수의 최소값을 나타냅니다.
- 데이터의 범위를 이해하는 데 도움을 줍니다.
- 데이터셋의 하한을 나타냅니다.

### 5. 25% (1사분위수, Q1)
- 전체 데이터 중 하위 25%가 이 값 이하임을 의미합니다.
- 데이터의 분포를 이해하는 데 도움이 됩니다.

### 6. 50% (중간값, Median)
- 전체 데이터의 중앙값입니다.
- 데이터의 중심을 나타내는 중요한 지표입니다.

### 7. 75% (3사분위수, Q3)
- 전체 데이터 중 하위 75%가 이 값 이하임을 의미합니다.
- 데이터의 분포와 범위를 이해하는 데 유용합니다.

### 8. max
- 각 변수의 최대값을 나타냅니다.
- 데이터의 범위의 상한을 제공합니다.
- 데이터셋의 최고점을 파악하는 데 중요합니다.

In [ ]:
print(titanic.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
titanic['age'] = titanic['age'].fillna(titanic['age'].median())
titanic['embarked'] = titanic['embarked'].fillna(titanic['embarked'].mode()[0])

print(titanic['age'].isnull().sum())
print(titanic['embarked'].isnull().sum())

0
0

Chained Assignment: titanic['age']와 같은 서브셋은 DataFrame의 복사본을 반환할 수 있습니다. 그 위에서 fillna 같은 메소드를 사용하면, 원본 DataFrame에 직접적인 영향을 주지 않을 수 있습니다.

Pandas 3.0 변화: 향후 Pandas 3.0 버전에서는 이 방식이 더 이상 작동하지 않을 것이므로, 지금부터 수정할 필요가 있습니다.

In [ ]:
titanic['sex'] = titanic['sex'].map({'male': 0, 'female': 1})
titanic['alive'] = titanic['alive'].map({'no': 1, 'yes': 0})
titanic['embarked'] = titanic['embarked'].map({'C': 0, 'Q': 1, 'S': 2,})

print(titanic['sex'].head())
print(titanic['alive'].head())
print(titanic['embarked'].head())

0    0
1    1
2    1
3    1
4    0
Name: sex, dtype: int64
0    1
1    0
2    0
3    0
4    1
Name: alive, dtype: int64
0    2
1    0
2    2
3    2
4    2
Name: embarked, dtype: int64

In [ ]:
titanic['family_size'] = titanic['sibsp'] + titanic['parch'] + 1
print(titanic['family_size'].head())

0    2
1    2
2    1
3    2
4    1
Name: family_size, dtype: int64

In [ ]:
titanic = titanic[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'family_size']]
X = titanic.drop('survived', axis=1)
y = titanic['survived']

In [ ]:
titanic.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  family_size
0         0       3    0  22.0      1      0   7.2500         2            2
1         1       1    1  38.0      1      0  71.2833         0            2
2         1       3    1  26.0      0      0   7.9250         2            1
3         1       1    1  35.0      1      0  53.1000         2            2
4         0       3    0  35.0      0      0   8.0500         2            1

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)


print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")

Accuracy: 0.8044692737430168
Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.86      0.84       105
           1       0.78      0.73      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179

X와 y의 표기법은 특정 규칙에 의한 것이 아니라, 관례에 따른 것입니다. 일반적으로 다음과 같이 사용됩니다:

X: 대문자 X는 독립 변수를 나타내는 데 사용됩니다. 이는 다차원 배열(예: 여러 특성의 DataFrame)일 때 주로 사용되며, 관례적으로 대문자로 표기합니다.
y: 소문자 y는 종속 변수를 나타냅니다. 일반적으로 단일 열(타겟 값)의 경우 소문자로 표기합니다.

train_test_split:
Scikit-learn 라이브러리의 함수로, 주어진 데이터를 훈련 세트와 테스트 세트로 나누는 데 사용됩니다. 모델의 성능을 평가하기 위해 데이터를 분할하는 데 중요합니다.

X:
독립 변수(피처) 데이터를 포함하는 DataFrame 또는 배열입니다. 일반적으로 모델에 입력으로 사용되는 데이터입니다.

y:
종속 변수(타겟) 데이터를 포함하는 Series 또는 배열입니다. 예측하고자 하는 값입니다.

test_size=0.2:
전체 데이터 중 20%를 테스트 세트로 사용하겠다는 의미입니다. 나머지 80%는 훈련 세트로 사용됩니다. 이 비율은 상황에 따라 조정할 수 있습니다.

random_state=42:
난수 생성기를 설정하여 데이터 분할의 재현성을 보장합니다. 동일한 random_state 값을 사용하면 같은 데이터 분할 결과를 얻을 수 있습니다. (42는 단순히 예시로 사용된 숫자이며, 다른 숫자도 가능합니다.)
출력:

X_train: 훈련 세트의 독립 변수.
X_test: 테스트 세트의 독립 변수.
y_train: 훈련 세트의 종속 변수.
y_test: 테스트 세트의 종속 변수.

In [ ]:
from sklearn.tree import DecisionTreeClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 스케일링
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 모델 생성 및 학습
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# 예측
y_pred = model.predict(X_test)

# 평가
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(f"Classification Report:\n{classification_report(y_test, y_pred)}")

Accuracy: 0.770949720670391
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.76      0.80       105
           1       0.70      0.78      0.74        74

    accuracy                           0.77       179
   macro avg       0.77      0.77      0.77       179
weighted avg       0.78      0.77      0.77       179

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 데이터 스케일링
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# XGBoost 모델 생성
xgb_model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)

# 모델 학습
xgb_model.fit(X_train_scaled, y_train)

# 예측
y_pred_xgb = xgb_model.predict(X_test_scaled)

# 평가
mse_xgb = mean_squared_error(y_test, y_pred_xgb)
print(f'XGBoost 모델의 MSE: {mse_xgb}')

XGBoost 모델의 MSE: 0.12981004899201257